version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ (AMQP) port
      - "15672:15672"   # RabbitMQ Management UI port
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASSWORD}

  config:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./config-repo:/config
    env_file:
      - .env
    networks:
      - keycloak-network
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    container_name: keycloak
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realms:/opt/keycloak/data/import
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - "8080:8080"
    command: start-dev
    restart: unless-stopped
    networks:
      - keycloak-network

volumes:
  keycloak_data:
networks:
  keycloak-network:
    driver: bridge