server:
  port: 8083

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_BUCKET_REGION}
  access-key-id: ${AWS_ACCESS_KEY_ID:}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY:}
video:
  upload:
    allowed-extensions: mp4,avi,mov,mkv,wmv,flv,webm
    max-file-size-mb: 500
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      enabled: true
  application:
    name: course-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}

  datasource:
    url: jdbc:postgresql://localhost:5432/courses
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  # JPA specific for user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    metadata-map:
      zone: zone1

logging:
  level:
    com.example.userservice: DEBUG
    org.hibernate.SQL: DEBUG