server:
  port: 8082

spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${CONFIG_URL}

  datasource:
    url: ${DATABASE_URL}/users
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}